name: Dev Batch Job Workflow
on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JobDefinitionName: "SunnyBatchJobDef"
      JobQueueName: "SunnyJobQueue"
      BatchJobRepoName: "sunny-batch-job-repo"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.HELIOS_DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HELIOS_DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Configure AWS CLI
        run: aws configure set default.region us-east-2

      - name: 'Install dotnet' 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install NuGet client
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get AWS account ID
        id: aws_account_id
        run: |
          aws_account_id=$(aws sts get-caller-identity --query "Account" --output text)
          echo "::set-output name=account_id::$aws_account_id"  
            
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          sed -i "s/{{RUNTIME_ENVIRONMENT}}/Development/g" Dockerfile
          # sed -i "s/COMMAND/--enableS3/g" Dockerfile
          docker build -f Dockerfile -t $ECR_REGISTRY/${{ env.BatchJobRepoName }} --build-arg AK="${{secrets.HELIOS_DEV_AWS_ACCESS_KEY_ID}}" --build-arg SK="${{secrets.HELIOS_DEV_AWS_SECRET_ACCESS_KEY }}" .
          docker push $ECR_REGISTRY/${{ env.BatchJobRepoName }}