name: Deploy to SBX

on:
  workflow_dispatch:
  #push:
   # branches:
    #  - develop

env:
  PROJECT_PATH: "user-api.sln"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.HELIOS_SBX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HELIOS_SBX_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install NuGet client
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build \
            --build-arg AK=$AWS_ACCESS_KEY_ID \
            --build-arg SK=$AWS_SECRET_ACCESS_KEY \
            -t $ECR_REGISTRY/helios-sbx-user-api-ecr:$GITHUB_RUN_ID .
          docker push $ECR_REGISTRY/helios-sbx-user-api-ecr:$GITHUB_RUN_ID
          sed -i "s/IMAGETAG/$GITHUB_RUN_ID/g" k8s-helios-sbx-user-api.yaml

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name helios-sbx-eks --region us-east-2
          kubectl apply -f k8s-helios-sbx-user-api.yaml
