name: Deploy to QA EKS Fargate 

on:
  workflow_dispatch:
  # merge_group:
  # push:
  #   branches:
  #     - release/1.2.0

env:
  PROJECT_PATH: 'helios-user-api.sln'      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send Microsoft Teams message
        id: teams_start
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL_QA }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "summary": "GitHub Action Notification",
                "themeColor": "0078D7",
                "sections": [
                  {
                    "activityTitle": "[Env: QA, Repo: ${{ github.event.repository.name }}]",
                    "activitySubtitle": "GitHub Action starting build/deploy",
                    "text": "[Link to PR or Commit](${{ github.event.pull_request.html_url || github.event.head_commit.url }})"
                  }
                ]
              }' \
          $TEAMS_WEBHOOK_URL
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.HELIOS_QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HELIOS_QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Configure AWS CLI
        run: aws configure set default.region us-east-2
        
      - name: 'Install dotnet' 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install NuGet client
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/user-qa-api:$GITHUB_RUN_ID --build-arg AK="${{secrets.HELIOS_QA_AWS_ACCESS_KEY_ID}}" --build-arg SK="${{secrets.HELIOS_QA_AWS_SECRET_ACCESS_KEY }}" .
          docker push $ECR_REGISTRY/user-qa-api:$GITHUB_RUN_ID
          docker tag $ECR_REGISTRY/user-qa-api:$GITHUB_RUN_ID userqaimage:$GITHUB_RUN_ID
          sed -i "s/IMAGETAG/$GITHUB_RUN_ID/g" k8s-helios-qa-user-api.yaml

      - name: Deploy to EKS Fargate
        run: |
          aws eks update-kubeconfig --name helios-qa --region us-east-2
          # kubectl apply -f helios-qa-user-api-external-secret.yaml
          kubectl apply -f k8s-helios-qa-user-api.yaml

      - name: Send Microsoft Teams message
        id: teams_end
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL_QA }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "summary": "GitHub Action Notification",
                "themeColor": "0078D7",
                "sections": [
                  {
                    "activityTitle": "[Env: QA, Repo: ${{ github.event.repository.name }}]",
                    "activitySubtitle": "GitHub Action build/deploy complete, result: ${{ job.status }}",
                    "text": "[Link to PR or Commit](${{ github.event.pull_request.html_url || github.event.head_commit.url }})"
                  }
                ]
              }' \
          $TEAMS_WEBHOOK_URL
      
      # - name: Configure UAT AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.HELIOS_UAT_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.HELIOS_UAT_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Configure UAT AWS CLI
      #   run: aws configure set default.region us-east-2

      # - name: Login to UAT Amazon ECR
      #   id: login-ecr-uat
      #   uses: aws-actions/amazon-ecr-login@v1 
          
      # - name: push Docker image to UAT ECR
      #   env:
      #     UAT_ECR_REGISTRY: ${{ steps.login-ecr-uat.outputs.registry }}
      #   run: |
      #     docker tag userqaimage:$GITHUB_RUN_ID $UAT_ECR_REGISTRY/helios-uat-user-api:$GITHUB_RUN_ID
      #     docker push $UAT_ECR_REGISTRY/helios-uat-user-api:$GITHUB_RUN_ID
      #     docker tag $UAT_ECR_REGISTRY/helios-uat-user-api:$GITHUB_RUN_ID userqaimage:$GITHUB_RUN_ID

      # - name: Configure Integ AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.HELIOS_INT_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.HELIOS_INT_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Configure Integ AWS CLI
      #   run: aws configure set default.region us-east-2

      # - name: Login to Integ Amazon ECR
      #   id: login-ecr-integ
      #   uses: aws-actions/amazon-ecr-login@v1 
          
      # - name: push Docker image to Integ ECR
      #   env:
      #     INTEG_ECR_REGISTRY: ${{ steps.login-ecr-integ.outputs.registry }}
      #   run: |
      #     docker tag userqaimage:$GITHUB_RUN_ID $INTEG_ECR_REGISTRY/helios-integ-user-api:$GITHUB_RUN_ID
      #     docker push $INTEG_ECR_REGISTRY/helios-integ-user-api:$GITHUB_RUN_ID
      #     docker tag $INTEG_ECR_REGISTRY/helios-integ-user-api:$GITHUB_RUN_ID userqaimage:$GITHUB_RUN_ID
    
      # - name: Configure Prod AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.HELIOS_PROD_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.HELIOS_PROD_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2

      # - name: Configure Prod AWS CLI
      #   run: aws configure set default.region us-east-2

      # - name: Login to Prod Amazon ECR
      #   id: login-ecr-prod
      #   uses: aws-actions/amazon-ecr-login@v1 
          
      # - name: push Docker image to Prod ECR
      #   env:
      #     PROD_ECR_REGISTRY: ${{ steps.login-ecr-prod.outputs.registry }}
      #   run: |
      #     docker tag userqaimage:$GITHUB_RUN_ID $PROD_ECR_REGISTRY/user-api:$GITHUB_RUN_ID
      #     docker push $PROD_ECR_REGISTRY/user-api:$GITHUB_RUN_ID
