name: Deploy to UAT EKS Fargate 

on:
  workflow_dispatch:
  # merge_group:
  # push:
  #   branches:
  #     - release/1.1.0

env:
  PROJECT_PATH: 'helios-wallet.api.sln'      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send Microsoft Teams message
        id: teams_start
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL_UAT }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "summary": "GitHub Action Notification",
                "themeColor": "0078D7",
                "sections": [
                  {
                    "activityTitle": "[Env: UAT, Repo: ${{ github.event.repository.name }}]",
                    "activitySubtitle": "GitHub Action starting build/deploy",
                    "text": "[Link to PR or Commit](${{ github.event.pull_request.html_url || github.event.head_commit.url }})"
                  }
                ]
              }' \
          $TEAMS_WEBHOOK_URL
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.HELIOS_UAT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.HELIOS_UAT_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Configure AWS CLI
        run: aws configure set default.region us-east-2
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/helios-uat-wallet-api:$GITHUB_RUN_ID --build-arg AK="${{secrets.HELIOS_UAT_AWS_ACCESS_KEY_ID}}" --build-arg SK="${{secrets.HELIOS_UAT_AWS_SECRET_ACCESS_KEY }}" .
          docker push $ECR_REGISTRY/helios-uat-wallet-api:$GITHUB_RUN_ID
          sed -i "s/IMAGETAG/$GITHUB_RUN_ID/g" k8s-helios-uat-wallet-api.yaml

      - name: Deploy to EKS Fargate
        run: |
          # sed -i "s/IMAGETAG/${{ vars.UAT_WALLET_API_IMAGEID }}/g" k8s-helios-uat-wallet-api.yaml
          aws eks update-kubeconfig --name helios-uat --region us-east-2
          kubectl apply -f k8s-helios-uat-wallet-api.yaml

      - name: Send Microsoft Teams message
        id: teams_end
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL_UAT }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "summary": "GitHub Action Notification",
                "themeColor": "0078D7",
                "sections": [
                  {
                    "activityTitle": "[Env: UAT, Repo: ${{ github.event.repository.name }}]",
                    "activitySubtitle": "GitHub Action build/deploy complete, result: ${{ job.status }}",
                    "text": "[Link to PR or Commit](${{ github.event.pull_request.html_url || github.event.head_commit.url }})"
                  }
                ]
              }' \
          $TEAMS_WEBHOOK_URL

